routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('studentProfile','student\StudentProfileController');
Route::resource('stuEditProfile','student\StudentEditProfileController');
Route::resource('sendBookReq','student\SendBookReqController');
Route::resource('bookedCourses','student\BookedCoursesController');
Route::resource('paymentHistory','student\PaymentHistoryController');
Route::resource('subjectDetail','student\SubjectDetailController');
Route::resource('sessionDetail','student\SessionDetailController');
Route::resource('sessionDetail2','student\SessionDetail2Controller');
Route::resource('stuAccountSetting','student\accountSettingController');

Route::resource('tutoreProfile','tutor\tutorProfileController');
Route::resource('tutorAccountSetting','tutor\AccountSettingController');
Route::resource('uploadCourse','tutor\UploadCourseController');

app/Http/Controllers/tutor/AccountSettingController.php
<?php

namespace App\Http\Controllers\tutor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\AccountDetail;
use Auth;

class AccountSettingController extends Controller
{
	/**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = AccountDetail::where('user_id',Auth::user()->id)->first();
		return view('tutor.accountSetting')->with($data);
	}

	public function update(Request $request, $id)
	{
		$param = $request->all();
		unset($param['_token'],$param['_method']);
		$update = AccountDetail::where('id',$id)->update($param);
		if($update)
		{
			return response()->json(['status' => 'success']);
		}
		else
		{
			return response()->json(['status' => 'error']);
		}
	}
}

app/Http/Controllers/tutor/TutorProfileController.php
<?php

namespace App\Http\Controllers\tutor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Auth;

class TutorProfileController extends Controller
{
	/**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}
	
	public function index()
	{
		$data['data'] = User::where('id',Auth::user()->id)->first();
		return view('tutor.profile')->with($data);
	}
}

app/Http/Controllers/tutor/UploadCourseController.php
<?php

namespace App\Http\Controllers\tutor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;

class UploadCourseController extends Controller
{
    /**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}
	
	public function index()
	{
		$data['data'] = "";
		return view('tutor.uploadCourse')->with($data);
	}
}

resources/views/tutor/accountSetting.blade.php
@extends('main')
@section('content')
<section class="contain_wapper" id="contain_wapper">
	<div class="home_wapper">
		<div class="inner-banner">
			<div class="container">
				<div class="banner-content">
					<h1>Account Settings</h1>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="account-settings">
				<form id="edit__form" method="POST">
					@csrf
					@method('PUT')
					<h2>Change Details</h2>
					<div class="form-group">
						<label for="email_id">Email ID *</label>
						<input type="email" class="form-control" id="email_id" name="email_id" placeholder="Enter Email ID" value="{{ $data->email_id }}">
					</div>
					<div class="form-group">
						<label for="password">Enter Password *</label>
						<input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
					</div>
					<div class="form-group">
						<label for="payment_method">Payment Method *</label>
						<input type="text" class="form-control" id="payment_method" name="payment_method" placeholder="Payment Gateway ID" value="{{ $data->payment_method }}">
					</div>
					<div class="form-group">
						<label for="card_detail">Credit/Debit Card Details *</label>
						<input type="text" class="form-control" id="card_detail" name="card_detail" placeholder="Credit/Debit Card Number" value="{{ $data->card_detail }}">
					</div>
					<div class="form-group row">
						<div class="form-group col-md-4">
							<input type="text" class="form-control" id="month" name="month" placeholder="Ex. Month" value="{{ $data->month }}">
						</div>
						<div class="form-group col-md-4">
							<input type="text" class="form-control" id="year" name="year" placeholder="Ex. Year" value="{{ $data->year }}">
						</div>
						<div class="form-group col-md-4">
							<input type="text" class="form-control" id="cvv" name="cvv" placeholder="CVV" value="{{ $data->cvv }}">
						</div>
					</div>
					<div class="form-group">
						<label for="notification_prefer">Notification Preferences *</label>
						<input type="text" class="form-control" id="notification_prefer" name="notification_prefer" placeholder="Notification Preferences" value="{{ $data->notification_prefer }}">
					</div>
					<div class="btn default"><a id="save" href="javascript:void(0)">Update</a></div>
				</form>
			</div>
		</div>
	</div>
</section>

<script>
	$("#save").on("click", function (e)
	{
		$.ajax({
			type: "POST",
			url: "{{ route('tutorAccountSetting.update', array($data->id)) }}",
			data: new FormData($('#edit__form')[0]),
			processData: false,
			contentType: false,
			success: function (data)
			{
				if (data.status === 'success') 
				{
					toastr.options.timeOut = 3000;
					toastr.options.fadeOut = 3000;
					toastr.options.progressBar = true;
					toastr.options.onHidden = function(){
						window.location = "{{ route('tutorAccountSetting.index') }}"
					};
					toastr["success"]("Account Details Updated Successfully", "Success");
				}
				else if(data.status === 'error') 
				{
					toastr.options.timeOut = 3000;
					toastr.options.fadeOut = 3000;
					toastr.options.progressBar = true;
					toastr["error"]("Opps.. Something Went Wrong.!", "Error");
				}
			}
		});
	});
</script>
@stop

resources/views/tutor/uploadCourse.blade.php
@extends('main')
@section('content')
<section class="contain_wapper" id="contain_wapper">
   <div class="home_wapper">
      <div class="inner-banner">
         <div class="container">
            <div class="banner-content">
               <h1>Upload New Course</h1>
            </div>
         </div>
      </div>
      <div class="container">
      <div class="account-settings">
         <form>
            <h2>Upload New Course</h2>
             <div class="form-group">
                <label for="EnterCourse">Course Title*</label>
                <input type="text" class="form-control" id="EnterCourse" placeholder="Enter Course Title">
              </div>
              <div class="form-group">
                <label for="SubTitle">Course SubTitle</label>
                <input type="text" class="form-control" id="SubTitle" placeholder="Enter Course SubTitle">
              </div>
              <div class="form-group">
                <label for="Category">Course Category*</label>
                <select id="Category" class="form-control">
			        <option selected>Select Course Category</option>
			        <option selected>Select Course</option>
			        <option selected>Select Category</option>
			      </select>
              </div>
              <div class="form-group">
                <label for="Category">Course Subcategory*</label>
                <select id="Category" class="form-control">
			        <option selected>Select Course Subcategory</option>
			        <option selected>Select Course</option>
			        <option selected>Select Subcategory</option>
			      </select>
              </div>
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Course Description *</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Enter Subject Description" rows="3"></textarea>
              </div>
              <div class="form-group">
              	<button class="small-btn form-btn">Add Batch</button>
              </div>
              <div class="form-check form-check-inline form-group">
              	<label class="form-check-label" for="recursive">It is recursive</label>
              	<div class="check-box">
				<input class="form-check-input ml-1" type="checkbox" id="recursive" value="option1">				  
			   	<label></label>
			   </div>
			   </div>
              <div class="form-group row">
                <div class="form-group col-md-6">
                	<label class="form-check-label" for="fromdate">From Date *</label>
                  	<div id="datepicker" class="input-group date" data-date-format="mm-dd-yyyy">
					    <input class="form-control" type="text" readonly />
					    <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
					</div>
                </div>
               <div class="form-group col-md-6">
                	<label class="form-check-label" for="fromdate">To Date *</label>
                  	<div id="datepicker2" class="input-group date" data-date-format="mm-dd-yyyy">
					    <input class="form-control" type="text" readonly />
					    <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
					</div>
                </div>
              </div>
              <div class="form-group">
                <label for="Attendees">No. of Attendees *</label>
                <input type="text" class="form-control" id="Attendees" placeholder="Enter No. of Attendees">
              </div>
              <div class="form-group">
                	<label class="form-check-label" for="fromdate">Select Days *</label>
                  	<div id="datepicker3" class="input-group date" data-date-format="dd-mm-yyyy">
					    <input class="form-control" type="text" readonly placeholder="Select Days" />
					    <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
					</div>
                </div>
                <div class="form-group">
                <label for="CourseFees">Course Fees *</label>
                <input type="text" class="form-control" id="CourseFees" placeholder="Enter Course Fees">
              </div>
              <div class="form-group">
                <label for="agegroup">Age Group *</label>
                <input type="text" class="form-control" id="agegroup" placeholder="Enter Age Group">
              </div>
               <div class="form-group">
               	<label class="orange-text">Session Details:</label>
               	<label class="orange-text">Batch 1:</label>
               </div>
               <div class="form-group">
                <label for="SelectSession">Session Date and Time *</label>
                <input type="text" class="form-control" id="SelectSession" placeholder="Select Session Date and Time">
              </div>
              <div class="form-group">
                <label for="Session">Session  Type (One to One/Group) *</label>
                <select id="Session" class="form-control">
			        <option selected>Select Session Type</option>
			        <option selected>Select Course</option>
			        <option selected>Select Session</option>
			      </select>
              </div>
              <div class="btn default second-btn opacity-5"><a id="save" href="javascript:void(0)">Add More Session</a></div>
				<div class="form-group">
              	<button class="small-btn form-btn">Add More Batch</button>
              </div>
              <div class="btn default"><a id="save" href="javascript:void(0)">Submit</a></div>
         </form>
      </div>
      </div>
   </div>
</section>

@stop