routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('studentProfile','student\StudentProfileController');
Route::resource('stuEditProfile','student\StudentEditProfileController');
Route::resource('sendBookReq','student\SendBookReqController');
Route::resource('bookedCourses','student\BookedCoursesController');
Route::resource('paymentHistory','student\PaymentHistoryController');
Route::resource('subjectDetail','student\SubjectDetailController');
Route::resource('sessionDetail','student\SessionDetailController');
Route::resource('sessionDetail2','student\SessionDetail2Controller');
Route::resource('stuAccountSetting','student\accountSettingController');

Route::resource('tutoreProfile','tutor\tutorProfileController');
Route::resource('tutorAccountSetting','tutor\AccountSettingController');
Route::resource('uploadCourse','tutor\UploadCourseController');

app/Http/Controllers/student/BookedCoursesController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BookedCoursesController extends Controller
{
    /**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = "";
		return view('student.bookedCourses')->with($data);
	}
}

app/Http/Controllers/student/PaymentHistoryController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PaymentHistoryController extends Controller
{
    /**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = "";
		return view('student.paymentHistory')->with($data);
	}
}

app/Http/Controllers/student/SendBookReqController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SendBookReqController extends Controller
{
	/**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = "";
		return view('student.sendBookReq')->with($data);
	}
}

app/Http/Controllers/student/SessionDetail2Controller.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SessionDetail2Controller extends Controller
{
    /**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = "";
		return view('student.sessionDetail2')->with($data);
	}
}

app/Http/Controllers/student/SessionDetailController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SessionDetailController extends Controller
{
	/**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = "";
		return view('student.sessionDetail')->with($data);
	}
}

app/Http/Controllers/student/StudentEditProfileController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Auth;

class StudentEditProfileController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data['data'] = User::where('id',Auth::user()->id)->first();
        return view('student.editProfile')->with($data);
    }

    public function update(Request $request, $id)
    {
        $param = $request->all();
        unset($param['_token'],$param['_method']);
        $update = User::where('id',$id)->update($param);
        if($update)
        {
            return response()->json(['status' => 'success']);
        }
        else
        {
            return response()->json(['status' => 'error']);
        }
    }
}

app/Http/Controllers/student/StudentProfileController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Auth;

class StudentProfileController extends Controller
{
	/**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = User::where('id',Auth::user()->id)->first();
		return view('student.profile')->with($data);
	}

}

app/Http/Controllers/student/SubjectDetailController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SubjectDetailController extends Controller
{
    /**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
    public function __invoke(Request $request)
    {
    	$this->middleware('auth');
    }

    public function index()
    {
    	$data['data'] = "";
    	return view('student.subjectDetail')->with($data);
    }
}

app/Http/Controllers/student/accountSettingController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\AccountDetail;
use Auth;

class AccountSettingController extends Controller
{
	/**
	 * Handle the incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['data'] = AccountDetail::where('user_id',Auth::user()->id)->first();
		return view('student.accountSetting')->with($data);
	}

	public function update(Request $request, $id)
	{
		$param = $request->all();
		unset($param['_token'],$param['_method']);
		$update = AccountDetail::where('id',$id)->update($param);
		if($update)
		{
			return response()->json(['status' => 'success']);
		}
		else
		{
			return response()->json(['status' => 'error']);
		}
	}
}

resources/views/student/accountSetting.blade.php
@extends('main')
@section('content')
<section class="contain_wapper" id="contain_wapper">
	<div class="home_wapper">
		<div class="inner-banner">
			<div class="container">
				<div class="banner-content">
					<h1>Account Settings</h1>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="account-settings">
				<form id="edit__form" method="POST">
					@csrf
					@method('PUT')
					<h2>Change Details</h2>
					<div class="form-group">
						<label for="email_id">Email ID *</label>
						<input type="email" class="form-control" id="email_id" name="email_id" placeholder="Enter Email ID" value="{{ $data->email_id }}">
					</div>
					<div class="form-group">
						<label for="password">Enter Password *</label>
						<input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
					</div>
					<div class="form-group">
						<label for="payment_method">Payment Method *</label>
						<input type="text" class="form-control" id="payment_method" name="payment_method" placeholder="Payment Gateway ID" value="{{ $data->payment_method }}">
					</div>
					<div class="form-group">
						<label for="card_detail">Credit/Debit Card Details *</label>
						<input type="text" class="form-control" id="card_detail" name="card_detail" placeholder="Credit/Debit Card Number" value="{{ $data->card_detail }}">
					</div>
					<div class="form-group row">
						<div class="form-group col-md-4">
							<input type="text" class="form-control" id="month" name="month" placeholder="Ex. Month" value="{{ $data->month }}">
						</div>
						<div class="form-group col-md-4">
							<input type="text" class="form-control" id="year" name="year" placeholder="Ex. Year" value="{{ $data->year }}">
						</div>
						<div class="form-group col-md-4">
							<input type="text" class="form-control" id="cvv" name="cvv" placeholder="CVV" value="{{ $data->cvv }}">
						</div>
					</div>
					<div class="form-group">
						<label for="notification_prefer">Notification Preferences *</label>
						<input type="text" class="form-control" id="notification_prefer" name="notification_prefer" placeholder="Notification Preferences" value="{{ $data->notification_prefer }}">
					</div>
					<div class="btn default"><a id="save" href="javascript:void(0)">Update</a></div>
				</form>
			</div>
		</div>
	</div>
</section>

<script>
	$("#save").on("click", function (e)
	{
		$.ajax({
			type: "POST",
			url: "{{ route('stuAccountSetting.update', array($data->id)) }}",
			data: new FormData($('#edit__form')[0]),
			processData: false,
			contentType: false,
			success: function (data)
			{
				if (data.status === 'success') 
				{
					toastr.options.timeOut = 3000;
					toastr.options.fadeOut = 3000;
					toastr.options.progressBar = true;
					toastr.options.onHidden = function(){
						window.location = "{{ route('stuAccountSetting.index') }}"
					};
					toastr["success"]("Account Details Updated Successfully", "Success");
				}
				else if(data.status === 'error') 
				{
					toastr.options.timeOut = 3000;
					toastr.options.fadeOut = 3000;
					toastr.options.progressBar = true;
					toastr["error"]("Opps.. Something Went Wrong.!", "Error");
				}
			}
		});
	});
</script>
@stop

resources/views/student/bookedCourses.blade.php
@extends('main')
@section('content')
<section class="contain_wapper" id="contain_wapper">
	<div class="home_wapper">
		<div class="inner-banner">
			<div class="container">
				<div class="banner-content">
					<h1>My Booked courses</h1>
				</div>
			</div>
		</div>
		<div class="booking-section">
		<div class="container">
			<div class="booing-header">
				<h2>My Booked courses</h2>
			</div>
			<div class="booing-courses">
				<h2>Upcoming courses</h2>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
			</div>
			<div class="booing-courses">
				<h2>Completed courses</h2>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="book-box">
						<div class="book-img">
							<img src="images/book-img.png" alt="Book" class="img-fluid">
							<span class="book-label">Web Design</span>
						</div>
						<div class="book-description">
							<h4>Graphics Design Bootcamp: Photoshop, illustrator, InDesign</h4>
							<label>Course SubTitle</label>
							<div class="rating">
								<em>5.0</em>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
								<i class='bx bxs-star' ></i>
							</div>
							<ul>
								<li>Teacher name : <strong>Name</strong></li>
								<li>Age Group : <strong>Age</strong></li>
								<li>Starts Date: <strong>04:10 PM</strong></li>
								<li>Fees : <strong>$149</strong></li>
							</ul>
							<button class="btn btn-dark-orange">View Details</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
</section>
@stop

resources/views/student/editProfile.blade.php
@extends('main')
@section('content')
<section class="contain_wapper" id="contain_wapper">
	<div class="home_wapper">
		<div class="inner-banner">
			<div class="container">
				<div class="banner-content">
					<h1>Edit Profile</h1>
				</div>
			</div>
		</div>
		<div class="user-profile edit-profile">
			<div class="container">
				<div class="user-header">
					<i class='bx bxs-edit-alt'></i>
					<img src="images/edit-icon.png">
				</div>
				<div class="user-title">
					<span>Student Details</span>
				</div>
				<div class="user-datalist">
					<form id="edit__form" method="POST">
						@csrf
						@method('PUT')
						<ul>
							<li>
								<span>First Name</span>
								<input type="text" placeholder="First Name" name="name" value="{{$data->name}}">
							</li>
							<li>
								<span>Last Name</span>
								<input type="text" placeholder="Last Name" name="lname" value="{{$data->lname}}">
							</li>
							<li>
								<span>Parents name</span>
								<input type="text" placeholder="Parents Name" name="parents_name" value="{{$data->parents_name}}">
							</li>
							<li>
								<span>Contact No.</span>
								<input type="text" placeholder="Contact No." name="contact" value="{{$data->contact}}">
							</li>
							<li>
								<span>Email ID</span>
								<input type="text" placeholder="Email Id" name="email" value="{{$data->email}}">
							</li>
							<li>
								<span>School Name</span>
								<input type="text" placeholder="School Name" name="school_name" value="{{$data->school_name}}">
							</li>
							<li>
								<span>Country Name</span>
								<select>
									<option>Select Country</option>
									<option>india</option>
									<option>Afghanistan</option>
									<option>Indonesia</option>
									<option>Iran</option>
									<option>Japan</option>
								</select>
							</li>
							<li>
								<span>City Name</span>
								<select>
									<option>Select Country</option>
									<option>Ahmedabad</option>
									<option>Surat</option>
									<option>Vadodara</option>
									<option>Rajkot</option>
									<option>Bhavnagar</option>
								</select>
							</li>
							<li>
								<span>State Name</span>
								<select>
									<option>Select State</option>
									<option>Andhra Pradesh</option>
									<option>Haryana</option>
									<option>Assam</option>
									<option>Gujarat</option>
									<option>Goa</option>
								</select>
							</li>

							<li>
								<span>Address</span>
								<textarea name="address">{{$data->address}}</textarea>
							</li>
						</ul>

						<div class="btn default"><a id="save" href="javascript:void(0)"> UPDATE PROFILE </a></div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
	$("#save").on("click", function (e)
	{
		$.ajax({
			type: "POST",
			url: "{{ route('stuEditProfile.update', array($data->id)) }}",
			data: new FormData($('#edit__form')[0]),
			processData: false,
			contentType: false,
			success: function (data)
			{
				if (data.status === 'success') 
				{
					toastr.options.timeOut = 3000;
					toastr.options.fadeOut = 3000;
					toastr.options.progressBar = true;
					toastr.options.onHidden = function(){
						window.location = "{{ route('studentProfile.index') }}"
					};
					toastr["success"]("User Updated Successfully", "Success");
				}
				else if(data.status === 'error') 
				{
					toastr.options.timeOut = 3000;
					toastr.options.fadeOut = 3000;
					toastr.options.progressBar = true;
					toastr["error"]("Opps.. Something Went Wrong.!", "Error");
				}
			}
		});
	});
</script>
@stop

resources/views/student/profile.blade.php
@extends('main')
@section('content')

<section class="contain_wapper" id="contain_wapper">
   <div class="home_wapper">
	  <div class="inner-banner">
		 <div class="container">
			<div class="banner-content">
			   <h1>My Profile</h1>
			</div>
		 </div>
	  </div>
	  <div class="user-profile">
		 <div class="container">
			<div class="user-header">
			   <img src="images/user-icon.png">
			</div>
			<div class="user-title">
			   <span>StudentDetails</span>
			</div>
			<div class="user-datalist">
			   <ul>
					<li>
						<strong>First Name:</strong>
						<span>{{$data->name}}</span>
					</li>
					<li>
						<strong>Last Name:</strong>
						<span>{{$data->lname}}</span>
					</li>
					<li>
						<strong>Parents name:</strong>
						<span>{{$data->parents_name}}</span>
					</li>
					<li>
						<strong>Contact No.:</strong>
						<span>{{$data->contact}}</span>
					</li>
					<li>
						<strong>Email ID:</strong>
						<span>{{$data->email}}</span>
					</li>
					<li>
						<strong>School:</strong>
						<span>{{$data->school_name}}</span>
					</li>
					<li>
						<strong>City:</strong>
						<span>{{$data->city}}</span>
					</li>
					<li>
						<strong>State:</strong>
						<span>{{$data->state}}</span>
					</li>
					<li>
						<strong>Country:</strong>
						<span>{{$data->country}}</span>
					</li>
					<li>
						<strong>Show Email Id/Phone Number:</strong>
						<span></span>
					</li>
					<li>
						<strong>Address:</strong>
						<span>{{$data->address}}</span>
					</li>
				</ul>
				<div class="btn default">
				  <a href="{{ route('stuEditProfile.index') }}">EDIT PROFILE</a>
				</div>
			</div>
		 </div>
	  </div>
   </div>
</section>

@stop