routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('studentProfile','student\StudentProfileController');
Route::resource('stuEditProfile','student\StudentEditProfileController');
Route::resource('sendBookReq','student\SendBookReqController');
Route::resource('bookedCourses','student\BookedCoursesController');
Route::resource('paymentHistory','student\PaymentHistoryController');
Route::resource('subjectDetail','student\SubjectDetailController');
Route::resource('sessionDetail','student\SessionDetailController');
Route::resource('sessionDetail2','student\SessionDetail2Controller');
Route::resource('stuAccountSetting','student\accountSettingController');

Route::resource('tutoreProfile','tutor\tutorProfileController');
Route::resource('tutorAccountSetting','tutor\AccountSettingController');
Route::resource('uploadCourse','tutor\UploadCourseController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer.blade.php
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="f-logo">
					<img src="images/logo.png" alt="Logo" class="img-fluid">
					<span>Get latest courses and offres alert on your phone</span>
				</div>
				<form>
					<div class="input-row">
						<input type="text" required placeholder="">
						<a href="javascript:void(0)">Subscribe Now</a>
					</div>
				</form>
				<div class="social-icon">
					<ul>
						<li><a href="javascript:void(0)"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
						<li><a href="javascript:void(0)"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-6">
				<div class="row no-gutters ">
					<div class="col-md-6">
						<div class="f-title">Company</div>
						<ul>
							<li><a href="javascript:void(0)">About</a></li>
							<li><a href="javascript:void(0)">Careers</a></li>
							<li><a href="javascript:void(0)">Mobile</a></li>
							<li><a href="javascript:void(0)">Blog</a></li>
							<li><a href="javascript:void(0)">How we work?</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<div class="f-title">Contact</div>
						<ul>
							<li><a href="javascript:void(0)">Help/FAQ</a></li>
							<li><a href="javascript:void(0)">Press</a></li>
							<li><a href="javascript:void(0)">Affilliates</a></li>
							<li><a href="javascript:void(0)">School owners</a></li>
							<li><a href="javascript:void(0)">Partners</a></li>
						</ul>
					</div>
					<div class="col-md-12">
						<span class="rights">All rights reserve. sitename.domain</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="https://unpkg.com/boxicons@2.0.9/dist/boxicons.js"></script>
<script src="js/bootstrap-select.js"></script>
<script src="js/browser_selector.js"></script>
<script src="js/AnimOnScroll.js"></script>
<script type="text/javascript" src="js/jquery.easing.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="js/script.js"></script>
<script>
 $("#datepicker").datepicker({ 
        autoclose: true, 
        todayHighlight: true
  }).datepicker('update', new Date());
   $("#datepicker2").datepicker({ 
        autoclose: true, 
        todayHighlight: true
  }).datepicker('update', new Date());
   $("#datepicker3").datepicker({ 
        autoclose: true, 
        todayHighlight: true
  }).datepicker('update', new Date());   
</script>
</body>
</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link
	href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
	rel="stylesheet">
	<link href="css/bootstrap.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="fonts/fonts.css" rel="stylesheet">
	<link href="fonts/font-awesome.min.css" rel="stylesheet">
	<link href="css/animate.min.css" rel="stylesheet">
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<link href="css/style.css" rel="stylesheet">
	<link href="css/responsive.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/js/toastr.min.js">
	</script>
	<script type="text/javascript">
		if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
			var msViewportStyle = document.createElement('style')
			msViewportStyle.appendChild(
				document.createTextNode(
					'@-ms-viewport{width:auto!important}'
					)
				)
			document.querySelector('head').appendChild(msViewportStyle)
		}
	</script>
</head>
<body>
	<div class="main_wapper">
		<header id="header">
			<div class="header_wapper">
				<div class="container">
					<nav class="navbar navbar-expand-lg">
						<div class="logo"><a href="#"><img src="images/logo.png" alt=""></a></div>
						<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="w-100  d-sm-block  d-md-block d-lg-none"></div>
						<div class="collapse navbar-collapse" id="navbarSupportedContent">
							<ul class="navbar-nav ml-auto">
								<li class="nav-item"><a href="#">About</a></li>
								<li class="nav-item"><a href="#">Category</a></li>
								<li class="nav-item"><a href="#">Blog</a></li>
								
								<li class="nav-item">
									<div class="dropdown">
										@guest
										@if (Route::has('register'))
										<a href="javascript:void(0)" class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Get Started</a>
										@endif
										@else
										<a href="javascript:void(0)" class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }}</a>
										@endguest

										@guest
										@if (Route::has('register'))
										<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
											@endif
											@else
											@if(Auth::user()->role_id == 1)
											<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
												@else
												<div class="dropdown-menu white-dropdown" aria-labelledby="dropdownMenuButton">
													@endif
													@endguest

													@guest
													<a class="dropdown-item" href="{{ route('login') }}">Log In</a>
													@if (Route::has('register'))
													<a class="dropdown-item" href="{{ route('register') }}">Register</a>
													@endif
													@else

													@if(Auth::user()->role_id == 1) <!-- 1 For Studemt -->
													<a class="dropdown-item" href="#">My History</a>
													<a class="dropdown-item" href="{{route('studentProfile.index')}}">My Profile</a>
													<a class="dropdown-item" href="{{route('sendBookReq.index')}}">My Send Booking Request</a>
													<a class="dropdown-item" href="{{route('bookedCourses.index')}}">My Booked Courses</a>
													<a class="dropdown-item" href="#">My Favorite Tutors</a>
													<a class="dropdown-item" href="#">My Given Reviews</a>
													<a class="dropdown-item" href="{{route('paymentHistory.index')}}">Payment History</a>
													<a class="dropdown-item" href="#">My Wallet</a>
													<a class="dropdown-item" href="{{ route('stuAccountSetting.index') }}">Account Setting</a>
													<a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
													<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
														@csrf
													</form>
													@else
													<a class="dropdown-item" href="{{route('tutoreProfile.index')}}">My Profile</a>
													<a class="dropdown-item" href="#">My Received Booking Request</a>
													<a class="dropdown-item" href="{{route('uploadCourse.index')}}">My Uploaded Course</a>
													<a class="dropdown-item" href="#">My Booked Session</a>
													<a class="dropdown-item" href="#">Availability Calendar</a>
													<a class="dropdown-item" href="#">Upload New Course</a>
													<a class="dropdown-item" href="#">My Receieved Reviews</a>
													<a class="dropdown-item" href="#">My Wallet</a>
													<a class="dropdown-item" href="#">Payment History</a>
													<a class="dropdown-item" href="{{ route('tutorAccountSetting.index') }}">Account Setting</a>
													<a class="dropdown-item" href="#">Search</a>
													<a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
													<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
														@csrf
													</form>
													@endif
													@endguest
												</div>

											</div>
										</li>

								<!-- <li class="nav-item">
									<div class="dropdown">
										<a href="javascript:void(0)" class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Get Started</a>
										<div class="dropdown-menu white-dropdown" aria-labelledby="dropdownMenuButton">
											<a class="dropdown-item" href="#">Action</a>
											<a class="dropdown-item" href="#">Another action</a>
											<a class="dropdown-item" href="#">Something else here</a>
										</div>

									</div>
								</li> -->

							</ul>
						</div>
					</nav>
				</div>
			</div>
		</header>